---
driver:
  name: vagrant
  network:
    - ["private_network", {type: "dhcp"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec
  attributes:
    # The 'http' inspec resource current executes on the host machine.
    # As we rely on it to verify that the liveness agent is updating the
    # faux Chef Automate we'll forward the port and execute the http
    # requests against localhost.
    port: 9292
    host: localhost

attributes:
  liveness-agent-test:
    automate:
      port: 9292

platforms:
  #
  # The test harness requires that the faux Automate server is running. Before
  # verifying any suite you need to make sure the Automate server is up.
  #
  #     kitchen converge required-faux-chef-automate
  #
  - name: faux-chef-automate
    driver:
      box: bento/ubuntu-16.04
      vm_hostname: fauxautomate
      network:
        # The 'http' inspec resource current executes on the host machine.
        # As we rely on it to verify that the liveness agent is updating the
        # faux Chef Automate we'll forward the port and execute the http
        # requests against localhost.
        - ["forwarded_port", {guest: 9292, host: 9292}]
        # This IP address is hardcoded into the test node chef-client config.
        # If you change it here you'll need to update the test cookbook.
        - ["private_network", {ip: "192.168.33.66"}]
  #
  # supported primary platforms
  #
  # debian
  #
  - name: debian-7.11
    provisioner:
      # chef-client 13 is currently broken on debian
      require_chef_omnibus: 12
    attributes:
      liveness-agent-test:
        automate:
          org_name: debian711
    verifier:
      attributes:
        org_name: debian711
  - name: debian-8.7
    provisioner:
      # chef-client 13 is currently broken on debian
      require_chef_omnibus: 12
    attributes:
      liveness-agent-test:
        automate:
          org_name: debian87
    verifier:
      attributes:
        org_name: debian87
  #
  # ubuntu
  #
  - name: ubuntu-12.04
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu1204
    verifier:
      attributes:
        org_name: ubuntu1204
  - name: ubuntu-12.04-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/ubuntu-12.04
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu120412
    verifier:
      attributes:
        org_name: ubuntu120412
  - name: ubuntu-14.04-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/ubuntu-12.04
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu140412
    verifier:
      attributes:
        org_name: ubuntu140412
  - name: ubuntu-14.04
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu1404
    verifier:
      attributes:
        org_name: ubuntu1404
  - name: ubuntu-16.04
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu1604
    verifier:
      attributes:
        org_name: ubuntu1604
  - name: ubuntu-16.04-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/ubuntu-16.04
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu160412
    verifier:
      attributes:
        org_name: ubuntu160412
  - name: ubuntu-16.10
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu1610
    verifier:
      attributes:
        org_name: ubuntu1610
  - name: ubuntu-16.10-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/ubuntu-16.10
    attributes:
      liveness-agent-test:
        automate:
          org_name: ubuntu161012
    verifier:
      attributes:
        org_name: ubuntu161012
  #
  # centos
  #
  - name: centos-5.11
    attributes:
      liveness-agent-test:
        automate:
          org_name: centos511
    verifier:
      attributes:
        org_name: centos511
  - name: centos-5.11-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/centos-5.11
    attributes:
      liveness-agent-test:
        automate:
          org_name: centos51112
    verifier:
      attributes:
        org_name: centos51112
  - name: centos-6.8
    attributes:
      liveness-agent-test:
        automate:
          org_name: centos68
    verifier:
      attributes:
        org_name: centos68
  - name: centos-6.8-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/centos-6.8
    attributes:
      liveness-agent-test:
        automate:
          org_name: centos6812
    verifier:
      attributes:
        org_name: centos6812
  - name: centos-7.3
    attributes:
      liveness-agent-test:
        org_name: centos73
    verifier:
      attributes:
        automate:
          org_name: centos73
  - name: centos-7.3-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/centos-7.3
    attributes:
      liveness-agent-test:
        automate:
          org_name: centos7312
    verifier:
      attributes:
        org_name: centos7312
  #
  # amazon linux
  #
  - name: amazon-linux
    driver:
      box: mvbcoding/awslinux
    attributes:
      liveness-agent-test:
        automate:
          org_name: amazonlinux
    verifier:
      attributes:
        org_name: amazonlinux
  - name: amazon-linux-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: mvbcoding/awslinux
    attributes:
      liveness-agent-test:
        automate:
          org_name: amazonlinux12
    verifier:
      attributes:
        org_name: amazonlinux12
  #
  # windows
  #
  - name: windows-2008-standard
    driver:
      box: chef/windows-server-2008r2-standard # private
    attributes:
      liveness-agent-test:
        automate:
          org_name: windows2008r2
    verifier:
      attributes:
        org_name: windows2008r2
        kitchen_dir: C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\
        windows: true
        sleep_seconds: 100
  - name: windows-2008-standard-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/windows-server-2008r2-standard # private
    attributes:
      liveness-agent-test:
        automate:
          org_name: windows2008r2
    verifier:
      attributes:
        org_name: windows2008r2
        kitchen_dir: C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\
        windows: true
        sleep_seconds: 100
  #
  # supported secondary platforms
  #
  # freebsd
  #
  - name: freebsd-10.3
    attributes:
      liveness-agent-test:
        automate:
          org_name: freebsd103
    verifier:
      attributes:
        org_name: freebsd103
  - name: freebsd-10.3-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/freebsd-10.3
    attributes:
      liveness-agent-test:
        automate:
          org_name: freebsd10312
    verifier:
      attributes:
        org_name: freebsd10312
  - name: freebsd-11.0
    attributes:
      liveness-agent-test:
        automate:
          org_name: freebsd11
    verifier:
      attributes:
        org_name: freebsd11
  - name: freebsd-11.0-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/freebsd-11.0
    attributes:
      liveness-agent-test:
        automate:
          org_name: freebsd1112
    verifier:
      attributes:
        org_name: freebsd1112
  #
  # fedora
  #
  - name: fedora-24
    attributes:
      liveness-agent-test:
        automate:
          org_name: fedora24
    verifier:
      attributes:
        org_name: fedora24
  - name: fedora-24-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/fedora-24
    attributes:
      liveness-agent-test:
        automate:
          org_name: fedora2412
    verifier:
      attributes:
        org_name: fedora2412
  #
  # unsupported platforms
  #
  - name: oracle-5.11
  - name: oracle-5.11-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/oracle-5.11
  - name: oracle-6.8
  - name: oracle-6.8-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/oracle-6.8
  - name: oracle-7.3
  - name: oracle-7.3-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/oracle-7.3
  - name: opensuse-leap-42.2
  - name: opensuse-leap-42.2-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: bento/opensuse-leap-42.2-12
  - name: macos-10.9
    driver:
      box: chef/macosx-10.9
  - name: macos-10.9-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/macosx-10.9
  - name: macos-10.10
    driver:
      box: chef/macosx-10.10
  - name: macos-10.10-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/macosx-10.10
  - name: macos-10.11
    driver:
      box: chef/macosx-10.11
  - name: macos-10.11-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/macosx-10.11
  - name: macos-10.12
    driver:
      box: chef/macos-10.12
  - name: macos-10.12-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/macos-10.12
  - name: solaris-10.11
    driver:
      box: chef/solaris-10.11
  - name: solaris-10.11-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/solaris-10.11
  - name: solaris-11.3
    driver:
      box: chef/solaris-11.3
  - name: solaris-11.3-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/solaris-11.3
  - name: sles-11-sp2
    driver:
      box: chef/sles-11-sp2-x86_64
  - name: sles-11-sp2-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/sles-11-sp2-x86_64
  - name: sles-12
    driver:
      box: chef/sles-12-x86_64
  - name: sles-12-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/sles-12-x86_64
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64
  - name: sles-12-sp1-12
    provisioner:
      require_chef_omnibus: 12
    driver:
      box: chef/sles-12-sp1-x86_64

  # platforms that are not being tested
  #
  #- name: rhel-5.11
  #- name: rhel-6.8
  #- name: rhel-7.11
  #- name: AIX?? lolz

suites:
  - name: required
    run_list:
      - recipe[liveness-agent-test::faux-automate]
    includes:
      - faux-chef-automate
  - name: supported
    run_list:
      - recipe[liveness-agent-test::test-client]
    attributes:
    verifier:
      inspec_tests:
        - test/integration/supported-platform
    includes:
      # primary platforms
      - debian-7.11
      - debian-8.7
      - ubuntu-12.04-12
      - ubuntu-12.04
      - ubuntu-14.04-12
      - ubuntu-14.04
      - ubuntu-16.04-12
      - ubuntu-16.04
      - ubuntu-16.04-12
      - ubuntu-16.10
      - ubuntu-16.10-12
      - centos-5.11
      - centos-5.11-12
      - centos-6.8
      - centos-6.8-12
      - centos-7.3
      - centos-7.3-12
      - amazon-linux
      - amazon-linux-12
      - windows-2008-standard
      - windows-2008-standard-12
      # secondary platforms
      - freebsd-10.3
      - freebsd-10.3-12
      - freebsd-11.0
      - freebsd-11.0-12
      - fedora-24
      - fedora-24-12
  - name: unsupported
    run_list:
      - recipe[liveness-agent-test::test-client]
    verifier:
      inspec_tests:
        - test/integration/unsupported-platform
    includes:
      - oracle-5.11
      - oracle-5.11-12
      - oracle-6.8
      - oracle-6.8-12
      - oracle-7.3
      - oracle-7.3-12
      - opensuse-leap-42.2
      - opensuse-leap-42.2-12
      - macos-10.9
      - macos-10.9-12
      - macos-10.10
      - macos-10.10-12
      - macos-10.11
      - macos-10.11-12
      - macos-10.12
      - macos-10.12-12
      - solaris-10.11
      - solaris-10.11-12
      - solaris-11.3
      - solaris-11.3-12
      - sles-11-sp2
      - sles-11-sp2-12
      - sles-12
      - sles-12-12
      - sles-12-sp1
      - sles-12-sp1-12
